name: 'Terraform'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.APPL_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_PW }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7

    - name: 'Terraform Format'
      run: terraform -chdir=./adds fmt -check -no-color
         
    - name: Terraform Init
      run: terraform -chdir=./adds init
 
    - name: 'Terraform Validate'
      run: terraform -chdir=./adds validate -no-color
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.7
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./adds"
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.7
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./adds"
